// SAJHA - Multi-Language support for major Indian languages
const lang = {
  en: {
    // Nav
    home: "Home",
    book: "Book",
    bookings: "My Bookings",
    contact: "Contact",
    menu: "Menu",
    langBtn: "हिंदी",

    // Hero
    heroTitle: "Connect Farmers. Grow Together.",
    heroSub: "Zero commission. Rent tractor & equipment easily.",
    bookNow: "Book Equipment",
    register: "Register",

    // Booking
    bookEquipment: "Book Equipment",
    whereNeed: "Where do you need?",
    selectEquipment: "Choose Equipment",
    tractor: "Tractor",
    harvester: "Harvester",
    plough: "Plough",
    irrigation: "Irrigation",
    cultivator: "Cultivator",
    seedDrill: "Seed Drill",
    thresher: "Thresher",
    sprayer: "Sprayer",
    rotavator: "Rotavator",
    drone: "Drone",
    jcb: "JCB Digger",
    reaper: "Straw Reaper",
    loader: "Cane Loader",
    leveler: "Laser Leveler",
    planter: "Potato Planter",
    transplanter: "Transplanter",
    selectDate: "Date",
    selectTime: "Time",
    duration: "How many hours?",
    hrs2: "2 hrs",
    hrs4: "4 hrs",
    hrs8: "8 hrs",
    hrs12: "12 hrs",
    day1: "1 day",
    total: "Total",
    bookBtn: "Book Now",
    available: "available",

    // Modals
    confirm: "Confirm",
    confirmBook: "Confirm & Book",
    successTitle: "Booked!",
    successMsg: "Your booking is confirmed.",
    bookingId: "Booking ID",
    viewDetails: "View",
    bookAnother: "Book Again",

    // About (simplified)
    aboutTitle: "About SAJHA",
    aboutSub: "For small farmers. No commission.",
    noCommission: "Zero Commission",
    noCommissionDesc: "No extra charges. You pay only rent.",
    directConnect: "Direct Connection",
    directConnectDesc: "Talk directly to equipment owner.",
    cashUpi: "Cash & UPI",
    cashUpiDesc: "Pay by cash or phone.",

    // Contact
    contactTitle: "Contact Us",
    phone: "Phone",
    call: "Call",
    address: "Address",

    // Bookings panel
    myBookings: "My Bookings",
    noBookings: "No bookings. Book your first equipment!",

    // Notifications
    notifications: "Notifications",

    // Alerts
    enterLocation: "Enter your village/area:",
    thankYou: "Thank you! We will call you soon.",
    // Owner Portal
    ownerPortal: "Owner Portal",
    listEquipment: "List Equipment",
    equipTitle: "Equipment Name",
    priceHr: "Price per Hour (₹)",
    availableFrom: "From Time",
    availableTo: "To Time",
    addListing: "List Now",
    myListings: "My Equipment",
    noListings: "No equipment listed yet.",
    listingSuccess: "Equipment listed successfully!",
    forOwners: "For Owners",

    // Driver Portal
    driverPortal: "Driver Portal",
    registerAsDriver: "Register as Driver",
    driverName: "Full Name",
    driverExperience: "Experience (Years)",
    driverContact: "Phone Number",
    driverLocation: "Home Village/Area",
    driverRate: "Daily Rate (₹)",
    addDriver: "Join as Driver",
    availableDrivers: "Available Drivers",
    noDrivers: "No drivers registered yet.",
    driverSuccess: "Registered successfully! Owners can now find you.",
    forDrivers: "For Drivers",
    yearsExp: "years exp",
    bestDeal: "Best Deal Found!",
    useThisDeal: "Use this deal",
    savePerHour: "Save ₹ per hour",
    // Club Portal
    clubPortal: "Farmers Club",
    joinClub: "Join a Club",
    createClub: "Create New Club",
    clubName: "Club Name",
    village: "Village",
    memberCount: "Members",
    joinBtn: "Join Now",
    myClubs: "Your Clubs",
    noClubs: "No clubs found. Create or join one!",
    clubSuccess: "Welcome to the club!",
    forClubs: "Farmers Club",
    clubBenefits: "Club Benefits",
    groupDiscount: "10% Group Discount",
    prioritySupport: "Priority Booking",

    // New Features
    weatherAlert: "Weather Alert",
    rainWarning: "Rain predicted. Plan carefully!",
    insurance: "Add Damage Protection (+₹50)",
    analytics: "My Analytics",
    income: "Income",
    savings: "Savings",
    govtSchemes: "Govt Schemes",
    mandiRates: "Mandi Rates",
    cropAdvisory: "Crop Advisory",
    demandAlert: "High demand expected!",
    payOnline: "Pay Online / UPI",
    refundInfo: "Refunds available on cancellation.",
    rateService: "Rate Service",
    voiceBtn: "Voice Command",
    pmsky: "PM Krishi Sinchai Yojana",

    // Newest Features
    scanCrop: "Scan Crop / Pest",
    smartIrrigation: "Field Moisture",
    irrigateNow: "Start Water",
    sellCrop: "Sell Your Produce",
    kisanChowpal: "Farmers Community",
    myRewards: "My Rewards (Coins)",
    inviteFriend: "Invite a Farmer",
    maintenance: "Equipment Health",
    audioGuide: "Listen to News",
    scanTitle: "Identify Pest",
    scanResult: "Diagnosis: Leaf Rust. Recommended: Organic Neem Oil spray.",
    trackBooking: "Track Booking",
    reachingIn: "Reaching your land in",
    onTheWay: "Driver is on the way",
    driverArrived: "Driver has arrived at your farm!",
  },
  hi: {
    // Nav
    home: "होम",
    book: "बुक करें",
    bookings: "मेरी बुकिंग",
    contact: "संपर्क",
    menu: "मेन्यू",
    langBtn: "English",

    // Hero
    heroTitle: "किसान जोड़ें। साथ बढ़ें।",
    heroSub: "बिना कमीशन। आसानी से ट्रैक्टर किराए पर लें।",
    bookNow: "उपकरण बुक करें",
    register: "रजिस्टर",

    // Booking
    bookEquipment: "उपकरण बुक करें",
    whereNeed: "कहाँ चाहिए?",
    selectEquipment: "उपकरण चुनें",
    tractor: "ट्रैक्टर",
    harvester: "हार्वेस्टर",
    plough: "हल",
    irrigation: "सिंचाई",
    cultivator: "कल्टीवेटर",
    seedDrill: "बीज ड्रिल",
    thresher: "थ्रेशर",
    sprayer: "स्प्रेयर",
    rotavator: "रोटावेटर",
    drone: "ड्रोन (Drone)",
    jcb: "जेसीबी (JCB)",
    reaper: "रीपर (Reaper)",
    loader: "लोडर (Loader)",
    leveler: "लेज़र लेवलर",
    planter: "प्लांटर",
    transplanter: "ट्रांसप्लांटर",
    selectDate: "तारीख",
    selectTime: "समय",
    duration: "कितने घंटे?",
    hrs2: "2 घंटे",
    hrs4: "4 घंटे",
    hrs8: "8 घंटे",
    hrs12: "12 घंटे",
    day1: "1 दिन",
    total: "कुल",
    bookBtn: "बुक करें",
    available: "उपलब्ध",

    // Modals
    confirm: "पुष्टि करें",
    confirmBook: "पुष्टि करें और बुक करें",
    successTitle: "बुक हो गया!",
    successMsg: "आपकी बुकिंग हो गई।",
    bookingId: "बुकिंग नंबर",
    viewDetails: "देखें",
    bookAnother: "फिर बुक करें",

    // About
    aboutTitle: "SAJHA के बारे में",
    aboutSub: "छोटे किसानों के लिए। बिना कमीशन।",
    noCommission: "जीरो कमीशन",
    noCommissionDesc: "कोई अतिरिक्त शुल्क नहीं। सिर्फ किराया।",
    directConnect: "सीधा संपर्क",
    directConnectDesc: "सीधे मालिक से बात करें।",
    cashUpi: "नकद और UPI",
    cashUpiDesc: "नकद या फोन से भुगतान।",

    // Contact
    contactTitle: "संपर्क करें",
    phone: "फोन",
    call: "कॉल करें",
    address: "पता",

    // Bookings
    myBookings: "मेरी बुकिंग",
    noBookings: "कोई बुकिंग नहीं। पहला उपकरण बुक करें!",

    // Notifications
    notifications: "सूचनाएं",

    // Alerts
    enterLocation: "अपना गाँव/क्षेत्र लिखें:",
    thankYou: "धन्यवाद! हम जल्द कॉल करेंगे।",

    // Owner Portal
    ownerPortal: "मालिक पोर्टल",
    listEquipment: "उपकरण लिस्ट करें",
    equipTitle: "उपकरण का नाम",
    priceHr: "किराया प्रति घंटा (₹)",
    availableFrom: "कब से",
    availableTo: "कब तक",
    addListing: "लिस्ट करें",
    myListings: "मेरे उपकरण",
    noListings: "अभी कोई उपकरण नहीं है।",
    listingSuccess: "उपकरण सफलतापूर्वक लिस्ट हो गया!",
    forOwners: "मालिकों के लिए",

    // Driver Portal
    driverPortal: "ड्राइवर पोर्टल",
    registerAsDriver: "ड्राइवर के रूप में जुड़ें",
    driverName: "पूरा नाम",
    driverExperience: "अनुभव (वर्ष)",
    driverContact: "फोन नंबर",
    driverLocation: "गाँव/क्षेत्र",
    driverRate: "प्रति दिन किराया (₹)",
    addDriver: "ड्राइवर बनें",
    availableDrivers: "उपलब्ध ड्राइवर",
    noDrivers: "अभी कोई ड्राइवर नहीं है।",
    driverSuccess: "सफलतापूर्वक रजिस्टर हो गया! मालिक अब आपको ढूंढ सकते हैं।",
    forDrivers: "ड्राइवरों के लिए",
    yearsExp: "वर्ष का अनुभव",
    bestDeal: "सबसे अच्छा ऑफर मिला!",
    useThisDeal: "यह ऑफर चुनें",
    savePerHour: "₹ प्रति घंटा की बचत",
    // Club Portal
    clubPortal: "किसान क्लब",
    joinClub: "क्लब में जुड़ें",
    createClub: "नया क्लब बनाएं",
    clubName: "क्लब का नाम",
    village: "गाँव",
    memberCount: "सदस्य",
    joinBtn: "अभी जुड़ें",
    myClubs: "आपके क्लब",
    noClubs: "कोई क्लब नहीं मिला। नया बनाएं!",
    clubSuccess: "क्लब में आपका स्वागत है!",
    forClubs: "किसान क्लब",
    clubBenefits: "क्लब के फायदे",
    groupDiscount: "10% ग्रुप छूट",
    prioritySupport: "बुकिंग में प्राथमिकता",

    // New Features
    weatherAlert: "मौसम की सूचना",
    rainWarning: "बारिश की संभावना। ध्यान से प्लान करें!",
    insurance: "नुकसान सुरक्षा जोड़ें (+₹50)",
    analytics: "मेरे आंकड़े",
    income: "आय",
    savings: "बचत",
    govtSchemes: "सरकारी योजनाएं",
    mandiRates: "मंडी भाव",
    cropAdvisory: "फसल सलाह",
    demandAlert: "भारी मांग की संभावना!",
    payOnline: "ऑनलाइन / UPI भुगतान",
    refundInfo: "कैंसिल करने पर रिफंड उपलब्ध।",
    rateService: "रेटिंग दें",
    voiceBtn: "वॉइस कमांड",
    pmsky: "PM कृषि सिंचाई योजना",

    // Newest Features
    scanCrop: "फसल की जांच",
    smartIrrigation: "मिट्टी की नमी",
    irrigateNow: "पानी शुरू करें",
    sellCrop: "अपनी फसल बेचें",
    kisanChowpal: "किसान चर्चा",
    myRewards: "मेरे इनाम (सिक्के)",
    inviteFriend: "किसान को जोड़ें",
    maintenance: "मशीन की सेहत",
    audioGuide: "खबरें सुनें",
    scanTitle: "बीमारी पहचानें",
    scanResult: "नतीजा: लीफ रस्ट। सलाह: नीम के तेल का छिड़काव करें।",
    trackBooking: "बुकिंग ट्रैक करें",
    reachingIn: "आपके खेत पर पहुँचने का समय",
    onTheWay: "ड्राइवर रास्ते में है",
    driverArrived: "ड्राइवर आपके खेत पर पहुँच गया है!",
  },
  bn: { // Bengali
    home: "হোম", book: "বুক করুন", bookings: "আমার বুকিং", contact: "যোগাযোগ", menu: "মেনু",
    heroTitle: "চাষীদের সংযোগ করুন। একসাথে বাড়ুন।", heroSub: "জিরো কমিশন। সহজে ট্রাক্টর ভাড়া নিন।",
    bookNow: "সরঞ্জাম বুক করুন", register: "নিবন্ধন", bookEquipment: "সরঞ্জাম বুক করুন", whereNeed: "আপনার কোথায় প্রয়োজন?",
    selectEquipment: "সরঞ্জাম চয়ন করুন", tractor: "ট্রাক্টর", harvester: "হারভেস্টার", plough: "লাঙ্গল",
    irrigation: "সেচ", cultivator: "কাল্টিভেটর", seedDrill: "বীজ ড্রিল", thresher: "থ্রেসার", sprayer: "স্প্রেয়ার",
    selectDate: "তারিখ", selectTime: "সময়", duration: "কত ঘন্টা?",
    hrs2: "২ ঘন্টা", hrs4: "৪ ঘন্টা", hrs8: "৮ ঘন্টা", hrs12: "১২ ঘন্টা", day1: "১ দিন",
    total: "মোট", bookBtn: "এখন বুক করুন", available: "উপলব্ধ",
    confirm: "নিশ্চিত করুন", confirmBook: "নিশ্চিত করুন এবং বুক করুন", successTitle: "বুক করা হয়েছে!",
    successMsg: "আপনার বুকিং নিশ্চিত করা হয়েছে।", bookingId: "বুকিং আইডি", viewDetails: "দেখুন", bookAnother: "আবার বুক করুন",
    aboutTitle: "SAJHA সম্পর্কে", aboutSub: "ক্ষুদ্র কৃষকদের জন্য। কোনো কমিশন নেই।",
    noCommission: "জিরো কমিশন", noCommissionDesc: "অতিরিক্ত কোনো চার্জ নেই। আপনি শুধু ভাড়া দেবেন।",
    directConnect: "সরাসরি সংযোগ", directConnectDesc: "সরঞ্জাম মালিকের সাথে সরাসরি কথা বলুন।",
    cashUpi: "ক্যাশ এবং ইউপিআই", cashUpiDesc: "নগদ বা ফোনের মাধ্যমে অর্থ প্রদান করুন।",
    contactTitle: "আমাদের সাথে যোগাযোগ করুন", phone: "ফোন", call: "কল করুন", address: "ঠিকানা",
    myBookings: "আমার বুকিং", noBookings: "কোনো বুকিং নেই। আপনার প্রথম সরঞ্জাম বুক করুন!",
    enterLocation: "আপনার গ্রাম/এলাকা লিখুন:", thankYou: "ধন্যবাদ! আমরা শীঘ্রই আপনাকে কল করব।",
    ownerPortal: "মালিক পোর্টাল", listEquipment: "সরঞ্জাম তালিকাভুক্ত করুন", equipTitle: "সরঞ্জামের নাম",
    priceHr: "প্রতি ঘন্টায় ভাড়া (₹)", availableFrom: "কখন থেকে", availableTo: "কখন পর্যন্ত",
    addListing: "এখন তালিকাভুক্ত করুন", myListings: "আমার সরঞ্জাম", noListings: "এখনও কোনো সরঞ্জাম তালিকাভুক্ত নেই।",
    listingSuccess: "সরঞ্জাম সফলভাবে তালিকাভুক্ত করা হয়েছে!", forOwners: "মালিকদের জন্য",
    driverPortal: "ড্রাইভার পোর্টাল", registerAsDriver: "ড্রাইভার হিসাবে নিবন্ধন করুন", driverName: "পুরো নাম",
    driverExperience: "অভিজ্ঞতা (বছর)", driverContact: "ফোন নম্বর", driverLocation: "গ্রাম/এলাকা",
    driverRate: "প্রতিদিনের ভাড়া (₹)", addDriver: "ড্রাইভার হিসাবে যোগ দিন", availableDrivers: "উপলব্ধ ড্রাইভার",
    noDrivers: "এখনও কোনো ড্রাইভার নিবন্ধিত নেই।", driverSuccess: "সফলভাবে নিবন্ধিত!", forDrivers: "ড্রাইভারদের জন্য", yearsExp: "বছরের অভিজ্ঞতা"
  },
  te: { // Telugu
    home: "హోమ్", book: "బుక్ చేయండి", bookings: "నా బుకింగ్స్", contact: "సంప్రదించండి", menu: "మెనూ",
    heroTitle: "రైతులను కలపండి. కలిసి ఎదగండి.", heroSub: "జీరో కమిషన్. ట్రాక్టర్ మరియు పరికరాలను సులభంగా అద్దెకు తీసుకోండి.",
    bookNow: "పరికరాలను బుక్ చేయండి", register: "నమోదు", bookEquipment: "పరికరాలను బుక్ చేయండి", whereNeed: "మీకు ఎక్కడ కావాలి?",
    selectEquipment: "పరికరాలను ఎంచుకోండి", tractor: "ట్రాక్టర్", harvester: "హార్వెస్టర్", plough: "నాగలి",
    irrigation: "నీటి పారుదల", cultivator: "కల్టివేటర్", seedDrill: "సీడ్ డ్రిల్", thresher: "థ్రెషర్", sprayer: "స్ప్రేయర్",
    selectDate: "తేదీ", selectTime: "సమయం", duration: "ఎన్ని గంటలు?",
    hrs2: "2 గంటలు", hrs4: "4 గంటలు", hrs8: "8 గంటలు", hrs12: "12 గంటలు", day1: "1 రోజు",
    total: "మొత్తం", bookBtn: "ఇప్పుడే బుక్ చేయండి", available: "అందుబాటులో ఉంది",
    confirm: "నిర్ధారించండి", confirmBook: "నిర్ధారించి బుక్ చేయండి", successTitle: "బుక్ చేయబడింది!",
    successMsg: "మీ బుకింగ్ నిర్ధారించబడింది.", bookingId: "బుకింగ్ ID", viewDetails: "చూడండి", bookAnother: "మళ్ళీ బుక్ చేయండి",
    aboutTitle: "SAJHA గురించి", aboutSub: "చిన్న రైతుల కోసం. ఎటువంటి కమిషన్ లేదు.",
    noCommission: "జీరో కమిషన్", noCommissionDesc: "అదనపు ఛార్జీలు లేవు. మీరు అద్దె మాత్రమే చెల్లిస్తారు.",
    directConnect: "నేరుగా కనెక్ట్ అవ్వండి", directConnectDesc: "పరికర యజమానితో నేరుగా మాట్లాడండి.",
    cashUpi: "నగదు మరియు UPI", cashUpiDesc: "నగదు లేదా ఫోన్ ద్వారా చెల్లించండి.",
    contactTitle: "మమ్మల్ని సంప్రదించండి", phone: "ఫోన్", call: "కాల్ చేయండి", address: "చిరునామా",
    myBookings: "నా బుకింగ్స్", noBookings: "బుకింగ్స్ లేవు. మీ మొదటి పరికరాన్ని బుక్ చేయండి!",
    enterLocation: "మీ గ్రామం/ప్రాంతం నమోదు చేయండి:", thankYou: "ధన్యవాదాలు! మేము త్వరలో మీకు కాల్ చేస్తాము.",
    ownerPortal: "యజమాని పోర్టల్", listEquipment: "పరికరాలను జాబితా చేయండి", equipTitle: "పరికరం పేరు",
    priceHr: "గంటకు ధర (₹)", availableFrom: "ఎప్పటి నుండి", availableTo: "ఎప్పటి వరకు",
    addListing: "ఇప్పుడే జాబితా చేయండి", myListings: "నా పరికరాలు", noListings: "ఇంకా పరికరాలు జాబితా చేయబడలేదు.",
    listingSuccess: "పరికరం విజయవంతంగా జాబితా చేయబడింది!", forOwners: "యజమానుల కోసం",
    driverPortal: "డ్రైవర్ పోర్టల్", registerAsDriver: "డ్రైవర్‌గా నమోదు అవ్వండి", driverName: "పూర్తి పేరు",
    driverExperience: "అనుభవం (సంవత్సరాలు)", driverContact: "ఫోన్ నంబర్", driverLocation: "గ్రామం/ప్రాంతం",
    driverRate: "రోజువారీ రేటు (₹)", addDriver: "డ్రైవర్‌గా చేరండి", availableDrivers: "అందుబాటులో ఉన్న డ్రైవర్లు",
    noDrivers: "ఇంకా డ్రైవర్లు నమోదు కాలేదు.", driverSuccess: "విజయవంతంగా నమోదయ్యారు!", forDrivers: "డ్రైవర్ల కోసం", yearsExp: "సంవత్సరాల అనుభవం"
  },
  mr: { // Marathi
    home: "होम", book: "बुक करा", bookings: "माझे बुकिंग", contact: "संपर्क", menu: "मेनू",
    heroTitle: "शेतकऱ्यांना जोडा. एकत्र वाढूया.", heroSub: "झिरो कमिशन. ट्रॅक्टर आणि अवजारे सहज भाड्याने घ्या.",
    bookNow: "अवजारे बुक करा", register: "नोंदणी", bookEquipment: "अवजारे बुक करा", whereNeed: "तुम्हाला कोठे हवे आहे?",
    selectEquipment: "अवजारे निवडा", tractor: "ट्रॅक्टर", harvester: "हार्वेस्टर", plough: "नांगर",
    irrigation: "सिंचन", cultivator: "कल्टिव्हेटर", seedDrill: "सीड ड्रिल", thresher: "थ्रेशर", sprayer: "स्प्रेअर",
    selectDate: "तारीख", selectTime: "वेळ", duration: "किती तास?",
    hrs2: "२ तास", hrs4: "४ तास", hrs8: "८ तास", hrs12: "१२ तास", day1: "१ दिवस",
    total: "एकूण", bookBtn: "आता बुक करा", available: "उपलब्ध",
    confirm: "निश्चित करा", confirmBook: "निश्चित करा आणि बुक करा", successTitle: "बुक झाले!",
    successMsg: "तुमचे बुकिंग निश्चित झाले आहे.", bookingId: "बुकिंग आयडी", viewDetails: "पहा", bookAnother: "पुन्हा बुक करा",
    aboutTitle: "SAJHA बद्दल", aboutSub: "छोट्या शेतकऱ्यांसाठी. कमिशन नाही.",
    noCommission: "झिरो कमिशन", noCommissionDesc: "विनासायास भाडे. फक्त किराया द्या.",
    directConnect: "थेट संपर्क", directConnectDesc: "अवजार मालकाशी थेट बोला.",
    cashUpi: "कॅश आणि UPI", cashUpiDesc: "नकद किंवा फोनद्वारे पैसे द्या.",
    contactTitle: "आमच्याशी संपर्क साधा", phone: "फोन", call: "कॉल करा", address: "पत्ता",
    myBookings: "माझे बुकिंग", noBookings: "बुकिंग नाही. तुमचे पहिले अवजार बुक करा!",
    enterLocation: "तुमचे गाव/क्षेत्र लिहा:", thankYou: "धन्यवाद! आम्ही लवकरच तुम्हाला कॉल करू.",
    ownerPortal: "मालक पोर्टल", listEquipment: "अवजारांची यादी करा", equipTitle: "अवजाराचे नाव",
    priceHr: "प्रति तास दर (₹)", availableFrom: "केव्हापासून", availableTo: "केव्हापर्यंत",
    addListing: "आता यादी करा", myListings: "माझी अवजारे", noListings: "अद्याप कोणतीही अवजारे नाहीत.",
    listingSuccess: "अवजाराची यशस्वी नोंद झाली!", forOwners: "मालकांसाठी",
    driverPortal: "ड्रायव्हर पोर्टल", registerAsDriver: "ड्रायव्हर म्हणून नोंदणी करा", driverName: "पूर्ण नाव",
    driverExperience: "अनुभव (वर्षे)", driverContact: "फोन नंबर", driverLocation: "गाव/क्षेत्र",
    driverRate: "दैनंदिन दर (₹)", addDriver: "ड्रायव्हर म्हणून सामील व्हा", availableDrivers: "उपलब्ध ड्रायव्हर",
    noDrivers: "अद्याप कोणीही ड्रायव्हर नाही.", driverSuccess: "यशस्वी नोंदणी झाली!", forDrivers: "ड्रायव्हर्ससाठी", yearsExp: "वर्षे अनुभव"
  },
  ta: { // Tamil
    home: "முகப்பு", book: "பதிவு செய்க", bookings: "எனது பதிவுகள்", contact: "தொடர்பு", menu: "பட்டியல்",
    heroTitle: "விவசாயிகளை இணைப்போம். இணைந்து வளர்வோம்.", heroSub: "ஜீரோ கமிஷன். டிராக்டர் மற்றும் கருவிகளை எளிதாக வாடகைக்கு எடுக்கலாம்.",
    bookNow: "கருவியைப் பதிவு செய்க", register: "பதிவு", bookEquipment: "கருவியைப் பதிவு செய்க", whereNeed: "உங்களுக்கு எங்கே தேவை?",
    selectEquipment: "கருவியைத் தேர்வு செய்க", tractor: "டிராக்டர்", harvester: "அறுவடை இயந்திரம்", plough: "ஏர்",
    irrigation: "நீர்ப்பாசனம்", cultivator: "கலப்பை", seedDrill: "விதைப்பான்", thresher: "கதிர் அடிக்கும் இயந்திரம்", sprayer: "தெளிப்பான்",
    selectDate: "தேதி", selectTime: "நேரம்", duration: "எத்தனை மணி நேரம்?",
    hrs2: "2 மணி", hrs4: "4 மணி", hrs8: "8 மணி", hrs12: "12 மணி", day1: "1 நாள்",
    total: "மொத்தம்", bookBtn: "இப்போதே பதிவு செய்", available: "கிடைக்கிறது",
    confirm: "உறுதிப்படுத்து", confirmBook: "உறுதி செய்து பதிவு செய்க", successTitle: "பதிவு செய்யப்பட்டது!",
    successMsg: "உங்கள் பதிவு உறுதி செய்யப்பட்டது.", bookingId: "பதிவு ஐடி", viewDetails: "பார்க்க", bookAnother: "மீண்டும் பதிவு செய்க",
    aboutTitle: "SAJHA பற்றி", aboutSub: "சிறு விவசாயிகளுக்காக. கமிஷன் இல்லை.",
    noCommission: "ஜீரோ கமிஷன்", noCommissionDesc: "கூடுதல் கட்டணம் இல்லை. வாடகை மட்டும் செலுத்தவும்.",
    directConnect: "நேரடித் தொடர்பு", directConnectDesc: "கருவி உரிமையாளரிடம் நேரடியாகப் பேசவும்.",
    cashUpi: "பணம் மற்றும் UPI", cashUpiDesc: "பணம் அல்லது போன் மூலம் பணம் செலுத்தலாம்.",
    contactTitle: "எங்களைத் தொடர்பு கொள்ளவும்", phone: "போன்", call: "அழைக்கவும்", address: "முகவரி",
    myBookings: "எனது பதிவுகள்", noBookings: "பதிவுகள் எதுவுமில்லை. உங்கள் முதல் கருவியைப் பதிவு செய்யுங்கள்!",
    enterLocation: "உங்கள் கிராமம்/பகுதியை உள்ளிடவும்:", thankYou: "நன்றி! நாங்கள் விரைவில் உங்களை அழைப்போம்.",
    ownerPortal: "உரிமையாளர் போர்டல்", listEquipment: "கருவியைப் பட்டியலிடவும்", equipTitle: "கருவியின் பெயர்",
    priceHr: "மணிக்கு விலை (₹)", availableFrom: "தொடங்கும் நேரம்", availableTo: "முடியும் நேரம்",
    addListing: "இப்போதே பட்டியலிடு", myListings: "எனது கருவிகள்", noListings: "இதுவரை எந்தக் கருவியும் பட்டியலிடப்படவில்லை.",
    listingSuccess: "கருவி வெற்றிகரமாகப் பட்டியலிடப்பட்டது!", forOwners: "உரிமையாளர்களுக்காக",
    driverPortal: "டிரைவர் போர்டல்", registerAsDriver: "டிரைவராகப் பதிவு செய்க", driverName: "முழு பெயர்",
    driverExperience: "அனுபவம் (ஆண்டுகள்)", driverContact: "போன் எண்", driverLocation: "கிராமம்/பகுதி",
    driverRate: "தினசரி விகிதம் (₹)", addDriver: "டிரைவராக சேரவும்", availableDrivers: "கிடைக்கும் டிரைவர்கள்",
    noDrivers: "டிரைவர்கள் யாரும் இதுவரை பதிவு செய்யவில்லை.", driverSuccess: "வெற்றிகரமாக பதிவு செய்யப்பட்டது!", forDrivers: "டிரைவர்களுக்காக", yearsExp: "ஆண்டுகள் அனுபவம்"
  },
  gu: { // Gujarati
    home: "હોમ", book: "બુક કરો", bookings: "મારું બુકિંગ", contact: "સંપર્ક", menu: "મેનુ",
    heroTitle: "ખેડૂતોને જોડો. સાથે મળીને વિકાસ કરો.", heroSub: "ઝીરો કમિશન. ટ્રેક્ટર અને સાધનો સરળતાથી ભાડે મેળવો.",
    bookNow: "સાધન બુક કરો", register: "નોંધણી", bookEquipment: "સાધન બુક કરો", whereNeed: "તમારે ક્યાં જરૂર છે?",
    selectEquipment: "સાધન પસંદ કરો", tractor: "ટ્રેક્ટર", harvester: "હાર્વેસ્ટર", plough: "હળ",
    irrigation: "સિંચાઈ", cultivator: "કલ્ટીવેટર", seedDrill: "સીડ ડ્રિલ", thresher: "થ્રેશર", sprayer: "સ્પ્રેયર",
    selectDate: "તારીખ", selectTime: "સમય", duration: "કેટલા કલાક?",
    hrs2: "૨ કલાક", hrs4: "૪ કલાક", hrs8: "૮ કલાક", hrs12: "૧૨ કલાક", day1: "૧ દિવસ",
    total: "કુલ", bookBtn: "અત્યારે બુક કરો", available: "ઉપલબ્ધ",
    confirm: "પુષ્ટિ કરો", confirmBook: "પુષ્ટિ કરી બુક કરો", successTitle: "બુક થઈ ગયું!",
    successMsg: "તમારું બુકિંગ કન્ફર્મ થઈ ગયું છે.", bookingId: "બુકિંગ આઈડી", viewDetails: "જુઓ", bookAnother: "ફરીથી બુક કરો",
    aboutTitle: "SAJHA વિશે", aboutSub: "નાના ખેડૂતો માટે. કોઈ કમિશન નથી.",
    noCommission: "ઝીરો કમિશન", noCommissionDesc: "કોઈ વધારાનો ચાર્જ નહીં. માત્ર ભાડું ચૂકવો.",
    directConnect: "સીધો સંપર્ક", directConnectDesc: "સાધનના માલિક સાથે સીધી વાત કરો.",
    cashUpi: "રોકડ અને UPI", cashUpiDesc: "રોકડ અથવા ફોન દ્વારા પેમેન્ટ કરો.",
    contactTitle: "અમારો સંપર્ક કરો", phone: "ફોન", call: "કોલ કરો", address: "સરનામું",
    myBookings: "મારું બુકિંગ", noBookings: "કોઈ બુકિંગ નથી. તમારું પહેલું સાધન બુક કરો!",
    enterLocation: "તમારું ગામ/વિસ્તાર લખો:", thankYou: "આભાર! અમે ટૂંક સમયમાં તમને કોલ કરીશું.",
    ownerPortal: "માલિક પોર્ટલ", listEquipment: "સાધનની યાદી બનાવો", equipTitle: "સાધનનું નામ",
    priceHr: "કલાક દીઠ દર (₹)", availableFrom: "ક્યારથી", availableTo: "ક્યાં સુધી",
    addListing: "અત્યારે યાદી બનાવો", myListings: "મારા સાધનો", noListings: "હજુ સુધી કોઈ સાધન યાદીમાં નથી.",
    listingSuccess: "સાધનની સફળતાપૂર્વક નોંધણી થઈ!", forOwners: "માલિકો માટે",
    driverPortal: "ડ્રાઈવર પોર્ટલ", registerAsDriver: "ડ્રાઈવર તરીકે નોંધણી કરો", driverName: "પૂરું નામ",
    driverExperience: "અનુભવ (વર્ષો)", driverContact: "ફોન નંબર", driverLocation: "ગામ/વિસ્તાર",
    driverRate: "દૈનિક દર (₹)", addDriver: "ડ્રાઈવર તરીકે જોડાઓ", availableDrivers: "ઉપલબ્ધ ડ્રાઈવર",
    noDrivers: "હજુ કોઈ ડ્રાઈવર નોંધાયેલ નથી.", driverSuccess: "સફળતાપૂર્વક નોંધણી થઈ!", forDrivers: "ડ્રાઈવરો માટે", yearsExp: "વર્ષનો અનુભવ"
  },
  kn: { // Kannada
    home: "ಹೋಮ್", book: "ಬುಕ್ ಮಾಡಿ", bookings: "ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು", contact: "ಸಂಪರ್ಕಿಸಿ", menu: "ಮೆನು",
    heroTitle: "ರೈತರನ್ನು ಜೋಡಿಸಿ. ಒಟ್ಟಿಗೆ ಬೆಳೆಯೋಣ.", heroSub: "ಝೀರೋ ಕಮಿಷನ್. ಟ್ರಾಕ್ಟರ್ ಮತ್ತು ಉಪಕರಣಗಳನ್ನು ಸುಲಭವಾಗಿ ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ.",
    bookNow: "ಉಪಕರಣ ಬುಕ್ ಮಾಡಿ", register: "ನೋಂದಣಿ", bookEquipment: "ಉಪಕರಣ ಬುಕ್ ಮಾಡಿ", whereNeed: "ನಿಮಗೆ ಎಲ್ಲಿ ಬೇಕು?",
    selectEquipment: "ಉಪಕರಣ ಆರಿಸಿ", tractor: "ಟ್ರಾಕ್ಟರ್", harvester: "ಹಾರ್ವೆಸ್ಟರ್", plough: "ನೇಗಿಲು",
    irrigation: "ನೀರಾವರಿ", cultivator: "ಕಲ್ಟಿವೇಟರ್", seedDrill: "ಸೀಡ್ ಡ್ರಿಲ್", thresher: "ತ್ರೆಶರ್", sprayer: "ಸ್ಪ್ರೇಯರ್",
    selectDate: "ದಿನಾಂಕ", selectTime: "ಸಮಯ", duration: "ಎಷ್ಟು ಗಂಟೆಗಳು?",
    hrs2: "2 ಗಂಟೆ", hrs4: "4 ಗಂಟೆ", hrs8: "8 ಗಂಟೆ", hrs12: "12 ಗಂಟೆ", day1: "1 ದಿನ",
    total: "ಒಟ್ಟು", bookBtn: "ಈಗಲೇ ಬುಕ್ ಮಾಡಿ", available: "ಲಭ್ಯವಿದೆ",
    confirm: "ಖಚಿತಪಡಿಸಿ", confirmBook: "ಖಚಿತಪಡಿಸಿ ಬುಕ್ ಮಾಡಿ", successTitle: "ಬುಕ್ ಮಾಡಲಾಗಿದೆ!",
    successMsg: "ನಿಮ್ಮ ಬುಕಿಂಗ್ ಖಚಿತವಾಗಿದೆ.", bookingId: "ಬುಕಿಂಗ್ ಐಡಿ", viewDetails: "ನೋಡಿ", bookAnother: "ಮತ್ತೆ ಬುಕ್ ಮಾಡಿ",
    aboutTitle: "SAJHA ಬಗ್ಗೆ", aboutSub: "ಸಣ್ಣ ರೈತರಿಗಾಗಿ. ಯಾವುದೇ ಕಮಿಷನ್ ಇಲ್ಲ.",
    noCommission: "ಝೀರೋ ಕಮಿಷನ್", noCommissionDesc: "ಹೆಚ್ಚುವರಿ ಶುಲ್ಕಗಳಿಲ್ಲ. ಬಾಡಿಗೆ ಮಾತ್ರ ಪಾವತಿಸಿ.",
    directConnect: "ನೇರ ಸಂಪರ್ಕ", directConnectDesc: "ಉಪಕರಣದ ಮಾಲೀಕರೊಂದಿಗೆ ನೇರವಾಗಿ ಮಾತನಾಡಿ.",
    cashUpi: "ನಗದು ಮತ್ತು UPI", cashUpiDesc: "ನಗದು ಅಥವಾ ಫೋನ್ ಮೂಲಕ ಪಾವತಿಸಿ.",
    contactTitle: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ", phone: "ಫೋನ್", call: "ಕರೆ ಮಾಡಿ", address: "ವಿಳಾಸ",
    myBookings: "ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು", noBookings: "ಯಾವುದೇ ಬುಕಿಂಗ್ ಇಲ್ಲ. ನಿಮ್ಮ ಮೊದಲ ಉಪಕರಣವನ್ನು ಬುಕ್ ಮಾಡಿ!",
    enterLocation: "ನಿಮ್ಮ ಗ್ರಾಮ/ಪ್ರದೇಶವನ್ನು ನಮೂದಿಸಿ:", thankYou: "ಧನ್ಯವಾದಗಳು! ನಾವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮಗೆ ಕರೆ ಮಾಡುತ್ತೇವೆ.",
    ownerPortal: "ಮಾಲೀಕರ ಪೋರ್ಟಲ್", listEquipment: "ಉಪಕರಣವನ್ನು ಪಟ್ಟಿ ಮಾಡಿ", equipTitle: "ಉಪಕರಣದ ಹೆಸರು",
    priceHr: "ಗಂಟೆಗೆ ಬೆಲೆ (₹)", availableFrom: "ಯಾವ ಸಮಯದಿಂದ", availableTo: "ಯಾವ ಸಮಯದವರೆಗೆ",
    addListing: "ಈಗಲೇ ಪಟ್ಟಿ ಮಾಡಿ", myListings: "ನನ್ನ ಉಪಕರಣಗಳು", noListings: "ಇನ್ನೂ ಯಾವುದೇ ಉಪಕರಣಗಳು ಪಟ್ಟಿಯಲ್ಲಿಲ್ಲ.",
    listingSuccess: "ಉಪಕರಣವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪಟ್ಟಿ ಮಾಡಲಾಗಿದೆ!", forOwners: "ಮಾಲೀಕರಿಗಾಗಿ",
    driverPortal: "ಚಾಲಕರ ಪೋರ್ಟಲ್", registerAsDriver: "ಚಾಲಕರಾಗಿ ನೋಂದಾಯಿಸಿ", driverName: "ಪೂರ್ಣ ಹೆಸರು",
    driverExperience: "ಅನುಭವ (ವರ್ಷಗಳು)", driverContact: "ಫೋನ್ ಸಂಖ್ಯೆ", driverLocation: "ಗ್ರಾಮ/ಪ್ರದೇಶ",
    driverRate: "ದೈನಂದಿನ ದರ (₹)", addDriver: "ಚಾಲಕರಾಗಿ ಸೇರಿ", availableDrivers: "ಲಭ್ಯವಿರುವ ಚಾಲಕರು",
    noDrivers: "ಇನ್ನೂ ಯಾವುದೇ ಚಾಲಕರು ನೋಂದಾಯಿಸಿಲ್ಲ.", driverSuccess: "ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ!", forDrivers: "ಚಾಲಕರಿಗಾಗಿ", yearsExp: "ವರ್ಷಗಳ ಅನುಭವ"
  },
  ml: { // Malayalam
    home: "ഹോം", book: "ബുക്ക് ചെയ്യുക", bookings: "എന്റെ ബുക്കിംഗുകൾ", contact: "ബന്ധപ്പെടുക", menu: "മെനു",
    heroTitle: "കർഷകരെ ബന്ധിപ്പിക്കുക. ഒന്നിച്ചു വളരാം.", heroSub: "സീറോ കമ്മീഷൻ. ട്രാക്ടറും ഉപകരണങ്ങളും എളുപ്പത്തിൽ വാടകയ്‌ക്കെടുക്കാം.",
    bookNow: "ഉപകരണം ബുക്ക് ചെയ്യുക", register: "രജിസ്റ്റർ", bookEquipment: "ഉപകരണം ബുക്ക് ചെയ്യുക", whereNeed: "നിങ്ങൾക്ക് എവിടെയാണ് ആവശ്യം?",
    selectEquipment: "ഉപകരണം തിരഞ്ഞെടുക്കുക", tractor: "ട്രാക്ടർ", harvester: "ഹാർവെസ്റ്റർ", plough: "കലപ്പ",
    irrigation: "ജലസേചനം", cultivator: "കൾട്ടിവേറ്റർ", seedDrill: "സീഡ് ഡ്രിൽ", thresher: "ത്രെഷർ", sprayer: "സ്പ്രേയർ",
    selectDate: "തീയതി", selectTime: "സമയം", duration: "എത്ര മണിക്കൂർ?",
    hrs2: "2 മണിക്കൂർ", hrs4: "4 മണിക്കൂർ", hrs8: "8 മണിക്കൂർ", hrs12: "12 മണിക്കൂർ", day1: "1 ദിവസം",
    total: "ആകെ", bookBtn: "ഇപ്പോൾ ബുക്ക് ചെയ്യുക", available: "ലഭ്യമാണ്",
    confirm: "ഉറപ്പാക്കുക", confirmBook: "ഉറപ്പാക്കി ബുക്ക് ചെയ്യുക", successTitle: "ബുക്ക് ചെയ്തു!",
    successMsg: "നിങ്ങളുടെ ബുക്കിംഗ് ഉറപ്പായി.", bookingId: "ബുക്കിംഗ് ഐഡി", viewDetails: "കാണുക", bookAnother: "ഒരിക്കൽ കൂടി ബുക്ക് ചെയ്യുക",
    aboutTitle: "SAJHA-യെക്കുറിച്ച്", aboutSub: "ചെറുകിട കർഷകർക്കായി. കമ്മീഷൻ ഇല്ല.",
    noCommission: "സീറോ കമ്മീഷൻ", noCommissionDesc: "അധിക ചാർജുകളില്ല. വാടക മാത്രം നൽകുക.",
    directConnect: "നേരിട്ടുള്ള ബന്ധം", directConnectDesc: "ഉടമയുമായി നേരിട്ട് സംസാരിക്കുക.",
    cashUpi: "ക്യാഷ് & UPI", cashUpiDesc: "പണമായോ ഫോൺ വഴിയോ പണമടയ്ക്കാം.",
    contactTitle: "ഞങ്ങളെ ബന്ധപ്പെടുക", phone: "ഫോൺ", call: "വിളിക്കുക", address: "വിലാസം",
    myBookings: "എന്റെ ബുക്കിംഗുകൾ", noBookings: "ബുക്കിംഗുകൾ ഒന്നുമില്ല. ആദ്യത്തെ ഉപകരണം ബുക്ക് ചെയ്യൂ!",
    enterLocation: "നിങ്ങളുടെ ഗ്രാമം/സ്ഥലം നൽകുക:", thankYou: "നന്ദി! ഞങ്ങൾ ഉടൻ വിളിക്കാം.",
    ownerPortal: "ഓണർ പോർട്ടൽ", listEquipment: "ഉപകരണം ലിസ്റ്റ് ചെയ്യുക", equipTitle: "ഉപകരണത്തിന്റെ പേര്",
    priceHr: "മണിക്കൂറിന് വില (₹)", availableFrom: "എപ്പോൾ മുതൽ", availableTo: "എപ്പോൾ വരെ",
    addListing: "ഇപ്പോൾ ലിസ്റ്റ് ചെയ്യുക", myListings: "എന്റെ ഉപകരണങ്ങൾ", noListings: "ഉപകരണങ്ങളൊന്നും ലിസ്റ്റ് ചെയ്തിട്ടില്ല.",
    listingSuccess: "ഉപകരണം വിജകരമായി ലിസ്റ്റ് ചെയ്തു!", forOwners: "ഉടമസ്ഥർക്കായി",
    driverPortal: "ഡ്രൈവർ പോർട്ടൽ", registerAsDriver: "ഡ്രൈവറായി രജിസ്റ്റർ ചെയ്യുക", driverName: "പൂർണ്ണരൂപം",
    driverExperience: "പരിചയം (വർഷം)", driverContact: "ഫോൺ നമ്പർ", driverLocation: "ഗ്രാമം/സ്ഥലം",
    driverRate: "പ്രതിദിന നിരക്ക് (₹)", addDriver: "ഡ്രൈവറായി ചേരുക", availableDrivers: "ലഭ്യമായ ഡ്രൈവർമാർ",
    noDrivers: "ഡ്രൈവർമാരാരും ഇതുവരെ രജിസ്റ്റർ ചെയ്തിട്ടില്ല.", driverSuccess: "വിജകരമായി രജിസ്റ്റർ ചെയ്തു!", forDrivers: "ഡ്രൈവർമാർക്കായി", yearsExp: "വർഷത്തെ പരിചയം"
  },
  pa: { // Punjabi
    home: "ਹੋਮ", book: "ਬੁੱਕ ਕਰੋ", bookings: "ਮੇਰੀ ਬੁਕਿੰਗ", contact: "ਸੰਪਰਕ", menu: "ਮੇਨੂ",
    heroTitle: "ਕਿਸਾਨਾਂ ਨੂੰ ਜੋੜੋ। ਇਕੱਠੇ ਵਧੋ।", heroSub: "ਜ਼ੀਰੋ ਕਮਿਸ਼ਨ। ਟ੍ਰੈਕਟਰ ਅਤੇ ਸੰਦ ਆਸਾਨੀ ਨਾਲ ਕਿਰਾਏ 'ਤੇ ਲਓ।",
    bookNow: "ਸੰਦ ਬੁੱਕ ਕਰੋ", register: "ਰਜਿਸਟਰ", bookEquipment: "ਸੰਦ ਬੁੱਕ ਕਰੋ", whereNeed: "ਤੁਹਾਨੂੰ ਕਿੱਥੇ ਚਾਹੀਦਾ ਹੈ?",
    selectEquipment: "ਸੰਦ ਚੁਣੋ", tractor: "ਟ੍ਰੈਕਟਰ", harvester: "ਹਾਰਵੈਸਟਰ", plough: "ਹਲ",
    irrigation: "ਸਿੰਚਾਈ", cultivator: "ਕਲਟੀਵੇਟਰ", seedDrill: "ਸੀਡ ਡਰਿੱਲ", thresher: "ਥ੍ਰੈਸ਼ਰ", sprayer: "ਸਪ੍ਰੇਅਰ",
    selectDate: "ਤਰੀਕ", selectTime: "ਸਮਾਂ", duration: "ਕਿੰਨੇ ਘੰਟੇ?",
    hrs2: "2 ਘੰਟੇ", hrs4: "4 ਘੰਟੇ", hrs8: "8 ਘੰਟੇ", hrs12: "12 ਘੰਟੇ", day1: "1 ਦਿਨ",
    total: "ਕੁੱਲ", bookBtn: "ਹੁਣੇ ਬੁੱਕ ਕਰੋ", available: "ਉਪਲਬਧ",
    confirm: "ਪੁਸ਼ਟੀ ਕਰੋ", confirmBook: "ਪੁਸ਼ਟੀ ਕਰਕੇ ਬੁੱਕ ਕਰੋ", successTitle: "ਬੁੱਕ ਹੋ ਗਿਆ!",
    successMsg: "ਤੁਹਾਡੀ ਬੁਕਿੰਗ ਪੱਕੀ ਹੋ ਗਈ ਹੈ।", bookingId: "ਬੁਕਿੰਗ ਆਈਡੀ", viewDetails: "ਦੇਖੋ", bookAnother: "ਦੁਬਾਰਾ ਬੁੱਕ ਕਰੋ",
    aboutTitle: "SAJHA ਬਾਰੇ", aboutSub: "ਛੋਟੇ ਕਿਸਾਨਾਂ ਲਈ। ਕੋਈ ਕਮਿਸ਼ਨ ਨਹੀਂ।",
    noCommission: "ਜ਼ੀਰੋ ਕਮਿਸ਼ਨ", noCommissionDesc: "ਕੋਈ ਵਾਧੂ ਖਰਚਾ ਨਹੀਂ। ਸਿਰਫ ਕਿਰਾਇਆ ਦਿਓ।",
    directConnect: "ਸਿੱਧਾ ਸੰਪਰਕ", directConnectDesc: "ਸੰਦ ਦੇ ਮਾਲਕ ਨਾਲ ਸਿੱਧੀ ਗੱਲ ਕਰੋ।",
    cashUpi: "ਕੈਸ਼ ਅਤੇ UPI", cashUpiDesc: "ਨਕਦ ਜਾਂ ਫੋਨ ਰਾਹੀਂ ਭੁਗਤਾਨ ਕਰੋ।",
    contactTitle: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ", phone: "ਫੋਨ", call: "ਕਾਲ ਕਰੋ", address: "ਪਤਾ",
    myBookings: "ਮੇਰੀ ਬੁਕਿੰਗ", noBookings: "ਕੋਈ ਬੁਕਿੰਗ ਨਹੀਂ। ਆਪਣਾ ਪਹਿਲਾ ਸੰਦ ਬੁੱਕ ਕਰੋ!",
    enterLocation: "ਆਪਣੇ ਪਿੰਡ/ਇਲਾਕੇ ਦਾ ਨਾਂ ਲਿਖੋ:", thankYou: "ਧੰਨਵਾਦ! ਅਸੀਂ ਜਲਦੀ ਹੀ ਤੁਹਾਨੂੰ ਕਾਲ ਕਰਾਂਗੇ।",
    ownerPortal: "ਮਾਲਕ ਪੋਰਟਲ", listEquipment: "ਸੰਦ ਦੀ ਸੂਚੀ ਬਣਾਓ", equipTitle: "ਸੰਦ ਦਾ ਨਾਂ",
    priceHr: "ਪ੍ਰਤੀ ਘੰਟਾ ਕਿਰਾਇਆ (₹)", availableFrom: "ਕਦੋਂ ਤੋਂ", availableTo: "ਕਦੋਂ ਤੱਕ",
    addListing: "ਹੁਣੇ ਸੂਚੀਬੱਧ ਕਰੋ", myListings: "ਮੇਰੇ ਸੰਦ", noListings: "ਅਜੇ ਕੋਈ ਸੰਦ ਸੂਚੀ ਵਿੱਚ ਨਹੀਂ ਹੈ।",
    listingSuccess: "ਸੰਦ ਸਫਲਤਾਪੂਰਵਕ ਰਜਿਸਟਰ ਹੋ ਗਿਆ!", forOwners: "ਮਾਲਕਾਂ ਲਈ",
    driverPortal: "ਡਰਾਈਵਰ ਪੋਰਟਲ", registerAsDriver: "ਡਰਾਈਵਰ ਵਜੋਂ ਰਜਿਸਟਰ ਕਰੋ", driverName: "ਪੂਰਾ ਨਾਂ",
    driverExperience: "ਤਜਰਬਾ (ਸਾਲ)", driverContact: "ਫੋਨ ਨੰਬਰ", driverLocation: "ਪਿੰਡ/ਇਲਾਕਾ",
    driverRate: "ਰੋਜ਼ਾਨਾ ਕਿਰਾਇਆ (₹)", addDriver: "ਡਰਾਈਵਰ ਵਜੋਂ ਸ਼ਾਮਲ ਹੋਵੋ", availableDrivers: "ਉਪਲਬਧ ਡਰਾਈਵਰ",
    noDrivers: "ਅਜੇ ਕੋਈ ਡਰਾਈਵਰ ਰਜਿਸਟਰਡ ਨਹੀਂ ਹੈ।", driverSuccess: "ਸਫਲਤਾਪੂਰਵਕ ਰਜਿਸਟਰਡ!", forDrivers: "ਡਰਾਈਵਰਾਂ ਲਈ", yearsExp: "ਸਾਲ ਦਾ ਤਜਰਬਾ"
  }
};
